Server: Update API routing
bryceknz/sanity-translations-experiment pull request #15
Opened 2023-09-22 15:53 UTC by bryceknz

- [➕ Swap Express.js for ElysiaJS](https://github.com/bryceknz/sanity-translations-experiment/commit/a4f7171b4b08edcd257398cd4e9cfef112517873)
- [♻️ Re-write server routing with ElysiaJS](https://github.com/bryceknz/sanity-translations-experiment/commit/f429ade598ec952c7ef156a027199ce85ce1600e)
- [✨ Translate content dynamically](https://github.com/bryceknz/sanity-translations-experiment/commit/cfc7b4897bc61966c5a4417b4b773bbc30d7f0f3)

Resolves #14.

2023-09-23 16:25 UTC, umxr requested changes
just on tweak, otherwise its all good 👍🏽. ElysiaJS is pretty neat

2023-09-23 16:25 UTC, umxr commented on server/index.ts
Could we add in the CORS plugin? https://elysiajs.com/plugins/cors.html - i had to update the express server to allow the FE to connect to the server. I presume it should just be a case of following the setup and 🤞🏽 it should just work

2023-09-24 17:52 UTC, bryceknz commented on server/index.ts
Ooh great idea! Does this look alright to you? My hope is it should allow any requests from `http://localhost:*` 🤞🏻:
```ts
const app = new Elysia()
  .use(cors({ origin: /^http:\/\/localhost:\d+$/ }))
```

2023-09-24 20:29 UTC, umxr commented on server/index.ts
Looks like it should work 🤞

2023-09-25 10:02 UTC, bryceknz commented on server/index.ts
Fixed: [🔒 Enabled CORS for `localhost`](https://github.com/bryceknz/sanity-translations-experiment/pull/15/commits/6a4081759d0c9472d67c66a9e6b1984128611c9a)

2023-09-25 10:57 UTC, umxr approved these changes
LGTM

2023-09-25 11:15 UTC, merged